version: '3.8'

services:
  # Metrics database
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_lab
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  # Visual panel
  grafana:
    image: grafana/grafana:latest
    container_name: grafana_lab
    ports:
      - "3000:3000"
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=admin # Default password